
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: Kiyo
      POSTGRES_PASSWORD: a1b2c3d4e5A
      POSTGRES_DB: content-share
    
    volumes:
      - ./db/db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
      - postgres_data:/var/lib/postgresql
  
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: content-share-nestjs-api
    restart: always
    environment:
      DATABASE_URL: postgresql://Kiyo:a1b2c3d4e5A@db:5432/content-share
    depends_on:
      - db
  
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: content-share-client
    restart: always
    environment:
      VITE_GOOGLE_API_KEY: AIzaSyCzZoAdvTdhUnvWE7irIgqtZeHv3tAil1c
      VITE_SPOTIFY_CLIENT_ID: f1759d9bdfed4120b3cce6f3556c9b3d
      VITE_SPOTIFY_CLIENT_SECRET: 87f0a2c752c145d6861c7125d7c5479c
      # VITE_BACKEND_SERVER_URL="https://sound-link.nk-1310.online/api/"
      VITE_BACKEND_SERVER_URL: "/api"
      VITE_WORKOS_CLIENT_ID: client_01K3Y3STRS1G027R10A32HWEJG
    depends_on:
      - server
      - db
    ports:
      - 80:80
    volumes:
      # Map your local Nginx config so you can update it without rebuilding the image
      - ./client/nginx.default.conf:/etc/nginx/conf.d/default.conf


volumes:
  postgres_data:
  webroot: